#!/usr/bin/env bash
#! Author: LyhourChhen
#! Email: chhenlyhour@gmail.com

printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
flutter format ./lib/*.dart
printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter formatter'
